"""initial

Revision ID: 0001
Revises:
Create Date: 2026-09-17 18:45:35.125029
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("classes", sa.JSON(), nullable=False),
        sa.Column("split_method", sa.String(), nullable=False),
        sa.Column("split_params", sa.JSON(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("log_path", sa.String(), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index("ix_job_created", ["created_at"], unique=False)
        batch_op.create_index("ix_job_state", ["state"], unique=False)

    op.create_table(
        "model",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("weights_path", sa.String(), nullable=False),
        sa.Column("base_weights", sa.String(), nullable=True),
        sa.Column("dataset_id", sa.String(length=36), nullable=True),
        sa.Column("hyperparameters", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("class_names", sa.JSON(), nullable=False),
        sa.Column("class_aliases", sa.JSON(), nullable=False),
        sa.Column("exports", sa.JSON(), nullable=False),
        sa.Column("artifacts", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("classes", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("preannotation_model_id", sa.String(length=36), nullable=True),
        sa.Column("import_defaults", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("image_ids", sa.JSON(), nullable=False),
        sa.Column("tiling", sa.JSON(), nullable=False),
        sa.Column("conf", sa.Float(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("folder", sa.String(), nullable=False),
        sa.Column("site", sa.String(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "image",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("capture_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lon", sa.Float(), nullable=True),
        sa.Column("alt", sa.Float(), nullable=True),
        sa.Column("phash", sa.String(length=16), nullable=True),
        sa.Column("group_key", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.create_index("ix_image_group", ["group_key"], unique=False)
        batch_op.create_index("ix_image_path", ["path"], unique=True)
        batch_op.create_index("ix_image_source", ["source_id"], unique=False)

    op.create_table(
        "box",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("image_id", sa.String(length=36), nullable=False),
        sa.Column("class_id", sa.String(length=36), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("w", sa.Float(), nullable=False),
        sa.Column("h", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("provenance_kind", sa.String(), nullable=False),
        sa.Column("model_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("query_run_id", sa.String(length=36), nullable=True),
        sa.Column("review_state", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("box", schema=None) as batch_op:
        batch_op.create_index("ix_box_image", ["image_id"], unique=False)
        batch_op.create_index("ix_box_query_run", ["query_run_id"], unique=False)
        batch_op.create_index("ix_box_review", ["review_state"], unique=False)

    op.create_table(
        "dataset_image",
        sa.Column("dataset_id", sa.String(length=36), nullable=False),
        sa.Column("image_id", sa.String(length=36), nullable=False),
        sa.Column("split", sa.String(), nullable=False),
        sa.Column("boxes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image.id"],
        ),
        sa.PrimaryKeyConstraint("dataset_id", "image_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset_image")
    with op.batch_alter_table("box", schema=None) as batch_op:
        batch_op.drop_index("ix_box_review")
        batch_op.drop_index("ix_box_query_run")
        batch_op.drop_index("ix_box_image")

    op.drop_table("box")
    with op.batch_alter_table("image", schema=None) as batch_op:
        batch_op.drop_index("ix_image_source")
        batch_op.drop_index("ix_image_path")
        batch_op.drop_index("ix_image_group")

    op.drop_table("image")
    op.drop_table("source")
    op.drop_table("query_run")
    op.drop_table("project")
    op.drop_table("model")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_state")
        batch_op.drop_index("ix_job_created")

    op.drop_table("job")
    op.drop_table("dataset")
    # ### end Alembic commands ###
